version: 2.1

orbs:
  maven: circleci/maven@3.2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "Build job"

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - maven/test

workflows:
  maven_test:
    jobs:
      - build
      - test